### PR TITLE
Create an indonesian test article

### PR DESCRIPTION
**Pull request by andrecahyadi**

### CODE REVIEW

**Comment by PardusEidolon** [comment]
nice :-)

**Comment by andrecahyadi** [comment]
How to merge these into the main branch? =D 

This branch has no conflicts with the base branch
Only those with [write access] to this repository can merge pull requests.

**Comment by PardusEidolon** [comment]
> How to merge these into the main branch? =D
> 
> This branch has no conflicts with the base branch Only those with [write access] to this repository can merge pull requests.

Ill set the permissions on the repository and give you access

**Comment by PardusEidolon** [comment]
@andrecahyadi you should be good to go. Ive just given you write access to this repository :)

**Pull request merged**
