### PR TITLE
Create _index.md

### PR DESCRIPTION
**Pull request by andrecahyadi**

### CODE REVIEW

**Comment by PardusEidolon** [comment]
👍👍👍

**Comment by andrecahyadi** [comment]
Hi, Jack. How to see what I've created in the web browser? Just like you did in the tutorial video. 

I saw on your browser address localhost:xxx something

**Comment by PardusEidolon** [comment]
@andrecahyadi you will have to follow the instructions in the `readme.md` file in this repository. Make sure you have git and hugo extended edition installed locally on your machine before you follow the repository instructions once you have set them up.

Then you can run a `hugo server` in your terminal and it should point a localhost adress at port 1313

**Comment by andrecahyadi** [comment]
@PardusEidolon Hi, Jack. I've managed to install Hugo extended in my laptop.
I'm able to run a sample website using command "hugo server" and open using web browser (localhost:1313).

I have installed git as well and still have no idea on how to install PostCSS and clone the github as mentioned in the readme.md, haha.

I'm using windows 11 64 bit

**Comment by PardusEidolon** [comment]
I also forgot to mention that you needed [Node.js](https://nodejs.org/en/download/) and [Npm](https://nodejs.org/en/download/) then you can run an `npm install postcss-cli` and `npm install autoprefixer`.

I also recommend that you get [git lfs](https://git-lfs.github.com/) just incase, because sometimes the website doesn't recognise the images stored in the repository that you clone. If you run into an error like that running `git lfs pull` seems to do the trick otherwise throw up an issue and label it a bug and ill sort it out for you.

**Pull request merged**
